### PR TITLE
adding tests for config

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by muffato** [comment]
Hi @vsoch . Speaking about settings, here is something that I found a a little bit weird. When writing the tests for #548, to change the `wrapper_scripts:templates` settings I couldn't set this key to `<value`>, I had to set `wrapper_scripts` to `templates:<value>`, cf https://github.com/singularityhub/singularity-hpc/blob/main/shpc/tests/test_wrappers.py#L45-L48

In this PR, it looks like I should have been able to put the whole key (joined by a colon) as the first parameter ?

**Comment by vsoch** [comment]
@muffato I'm glad you brought this up! So my intuition would be to do `set <name> <value>` but it looks like the current design is intended to parse each extra arg of "set" separately, allowing you to do:

```bash
$ shpc confg set field1:value2 field2:value2
```

But perhaps we should limit it to setting one thing, and then always require a group of two?

```

```bash
$ shpc confg set field1 value2
```
So then your example would work like:

```bash
$ shpc config set wrapper_scripts:templates value
```
Would that be a better interaction?

**Comment by vsoch** [comment]
okay check out https://github.com/singularityhub/singularity-hpc/pull/562/commits/105747d116342f9b3cf623cd37a22b6c83bf5395 - it should work for both! Let me know if you want me to add more tests.

**Comment by muffato** [comment]
I've done some tests. The particular behaviour I was talking about ( https://github.com/singularityhub/singularity-hpc/blob/main/shpc/tests/test_wrappers.py#L45-L48 ) was actually already fixed by 676660a21. `client.settings.set("wrapper_scripts:templates", "/path/to/templates")` now works.

Besides changing the CLI, 105747d116342f9b3cf623cd37a22b6c83bf5395 improves the way the changes are reported

_before_:
```
$ shpc config set wrapper_scripts:templates:/path/to/wrappers_templates
Updated wrapper_scripts to be templates:/path/to/wrappers_templates
```
_after_:
```
$ shpc config set wrapper_scripts:templates:/path/to/wrappers_templates
Updated wrapper_scripts:templates to be /path/to/wrappers_templates
```

Regarding the CLI itself, `shpc set key:subkey value` is more natural, but I didn't see it as a priority to be changed. 
Could you change the help message too ? Currently it's still advising the old syntax
```
$ shpc config set --help
usage: shpc config [-h] [--central] [params ...]

update configuration settings. Use set or get to see or set information.

positional arguments:
  params      Set or get a config value, edit the config, add or remove a list variable, or create a user-specific config.
              shpc config set key:value
              shpc config get key
              shpc edit
              shpc config inituser
              shpc config add registry:/tmp/registry
              shpc config remove registry:/tmp/registry

optional arguments:
  -h, --help  show this help message and exit
  --central   make edits to the central config file.
```

**Comment by vsoch** [comment]
yep on it!

**Comment by vsoch** [comment]
All set! https://github.com/singularityhub/singularity-hpc/pull/562/commits/a33593129efe4cad60f4fc5676526312eb4f46f2

I also added tests (for both formats) for add/remove.

**Review by muffato — APPROVED** [review]

**Pull request merged**
