### PR TITLE
Fix to respect SINGULARITY_OPTS and SINGULARITY_COMMAND_OPTS

### PR DESCRIPTION
**Pull request by surak**
This will make it tcsh-compliant while still respecting user's values.

### CODE REVIEW

**Comment by surak** [comment]
If this one works, I can do it for all other modules

**Comment by vsoch** [comment]
Awesome, let's give it a test!

**Comment by vsoch** [comment]
and sorry stepped away from my computer for a bit :)

**Comment by surak** [comment]
Someone with tcl familiarity can easily reproduce this mr for the old tcl stuff

**Comment by vsoch** [comment]
@surak here is some quick searching! https://stackoverflow.com/questions/37085392/tcl-how-to-check-if-environment-variable-already-set

**Comment by vsoch** [comment]
So how about changing / trying:

```
setenv PODMAN_OPTS ""
setenv PODMAN_COMMAND_OPTS ""
```
to
```
if { ![info exists ::env(PODMAN_OPTS)] } {
    setenv PODMAN_OPTS ""
} 
if { ![info exists ::env(PODMAN_COMMAND_OPTS)] } {
    setenv PODMAN_COMMAND_OPTS ""
} 
```
and the same for the singularity variants.

**Comment by vsoch** [comment]
@surak Ive added gpu to PyTorch and two new gpu tags for tensorflow:  https://github.com/singularityhub/singularity-hpc/pull/484/files

**Comment by marcodelapierre** [comment]
@surak I have tested your current LUA edit with Lmod v 8.3.1, and it does not work for me.
I suggest the following:
```
if not os.getenv("PODMAN_OPTS") then setenv ("PODMAN_OPTS", "") end
if not os.getenv("PODMAN_COMMAND_OPTS") then setenv ("PODMAN_COMMAND_OPTS", "") end
```
and same for Singularity

**Comment by marcodelapierre** [comment]
@vsoch  I have tested your TCL implementation with quite an old Modules version, 3.2.10.6, and it DOES work!

**Comment by vsoch** [comment]
Holy schmokes first try! I’ll add to the PR here and try to update the lua with your suggestion!

**Comment by vsoch** [comment]
Updated! https://github.com/singularityhub/singularity-hpc/pull/483/files

**Comment by surak** [comment]
> @surak I have tested your current LUA edit with Lmod v 8.3.1, and it does not work for me. I suggest the following:
> ```
> if not os.getenv("PODMAN_OPTS") then setenv ("PODMAN_OPTS", "") end
> if not os.getenv("PODMAN_COMMAND_OPTS") then setenv ("PODMAN_COMMAND_OPTS", "") end
> ```
> and same for Singularity

Sure, but this is weird. Are you using an older version of Lua? Lmod 8 defaults to Lua 5.2+ in most distributions. I'm happy with your changes.

**Comment by surak** [comment]
This can be merged!

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
Thank you @surak and @marcodelapierre ! https://pypi.org/project/singularity-hpc/0.0.41/

**Comment by marcodelapierre** [comment]
> > @surak I have tested your current LUA edit with Lmod v 8.3.1, and it does not work for me. I suggest the following:
> > ```
> > if not os.getenv("PODMAN_OPTS") then setenv ("PODMAN_OPTS", "") end
> > if not os.getenv("PODMAN_COMMAND_OPTS") then setenv ("PODMAN_COMMAND_OPTS", "") end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and same for Singularity
> 
> Sure, but this is weird. Are you using an older version of Lua? Lmod 8 defaults to Lua 5.2+ in most distributions. I'm happy with your changes.

Sorry @surak , I could not get back to this until today. The system I used for the test has Lmod 8.3.1 and Lua 5.3... not sure why there is discrepancy of behaviour. Glad it works for you, too, though!

**Pull request merged**
