### PR TITLE
make default containers directory alongside modules for faster loading

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by marcodelapierre** [comment]
containers and modules distinct by default : I second this, it's the first SHPC configuration I edit when I deploy it!

**Comment by marcodelapierre** [comment]
I think this is the line that needs fixing to have the test working:

https://github.com/singularityhub/singularity-hpc/blob/change-default-container-dir/shpc/tests/test_settings.py#L35

Now:
```
    assert not settings.container_base
```

Fix I think:
```
    assert settings.container_base == "$root_dir/containers"
```

**Comment by vsoch** [comment]
@marcodelapierre all set!

**Comment by marcodelapierre** [comment]
looks good!

**Pull request merged**
