### PR TITLE
Add support for singularity_options and docker_options

### PR DESCRIPTION
**Pull request by vsoch**
This will address #439 by adding singularity_options and docker_options.

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by marcodelapierre** [comment]
Gone through it, I have done some suggested changes, see PR #443 :

- Shall Podman be highlighted more than Docker, considering HPC is mostly being targeted here? I am suggesting to use `podman_options` instead of `docker_options` - few changes here and there in my commit

- missing line `.. code-block:: yaml` and subsequent newline at line 185 of `docs/getting_started/developer-guide.rst`

**Comment by marcodelapierre** [comment]
There's just one minor leftover fix:

missing line `.. code-block:: yaml` and subsequent newline at line 185 of `docs/getting_started/developer-guide.rst`

**Comment by vsoch** [comment]
@marcodelapierre I must be super tired because I don't see it locally!

image

**Comment by vsoch** [comment]
oh wait I'm on the wrong branch, hold! lol

**Comment by vsoch** [comment]
okay got it :)

**Comment by vsoch** [comment]
Good to go @marcodelapierre ? I just saw your new issue, and I think that's a great idea (although I need to go to sleep now!) so my thinking is that we should merge here, not release, and then I'll work on this new feature over the weekend and draft a new release after that. Let me know your thoughts!

**Comment by marcodelapierre** [comment]
sure good to go! 
and I agree, the other open issues on x11/home features might need further thinking, so likely for a future release

**Pull request merged**
